### ISSUE TITLE
Getting Error : Apple Mach-O Linker Error Group 

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-ios#69]
Hi,

I have tried to integrate Rollbar framework inside my application but getting the Apple Mach-O Linker Error Group  error while building the application.

Steps that i have followed.
Without Cocoapods

1. Download the Rollbar framework.

2. Extract the Rollbar directory in the zip file to your Xcode project directory.

3. In Xcode, select File -> Add Files to "[your project name]" and choose the Rollbar directory from step 2.

Note: if step three doesn't work you can also extract the Rollbar directory anywhere, and drag the .framework files into XCode, allowing XCode to correctly configure the Frameworks.

4. Added the below code fragment inside Bridging-Header file.
5. Added the below code fragment inside AppDelegate. 

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    let config: RollbarConfiguration = RollbarConfiguration()
    config.environment = "production"

    Rollbar.initWithAccessToken("POST_CLIENT_ITEM_ACCESS_TOKEN", configuration: config)

    return true
}

While building the app getting error please help me out. Here i have attached screen shot of error.

![rollbarerror](https://user-images.githubusercontent.com/32199575/35863960-541ad668-0b76-11e8-904d-73413361016d.png)

Thanks.

Wahid Ali

**Comment by rivkahstandig3636** [comment]
Hi @RollbarExample, we'll take a look into this and get back to you ASAP

**Comment by Lebron1992** [comment]
I am also getting the same error!

**Comment by laeroah** [comment]
@rivkahstandig3636 hi, do we have any updates on this?

**Comment by rivkahstandig3636** [comment]
@laeroah Not yet, I'm sorry. :( @rokob Can you please take a look into this issue?

**Comment by rokob** [comment]
I know what this is, working on it. I will update this when it is fixed. Just realized that a whole bunch of seemingly unrelated things are all related so hopefully will have something soon.l

**Comment by rokob** [comment]
Okay, there is a new release up (https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha6) with a new zip file. You need to add `libc++` to your link binary with libraries phase and add `-ObjC` to your "Other Linker Flags" section. This is included now as part of the installation instructions in the README. There was a problem with the build process that generated the framework binary that I believe is now fixed. I'm going to leave this open issue for a bit in case other problems arise.

**Comment by RollbarExample** [comment]
hey still getting the same error.

Below the steps that i have followed.
1. Downloaded fresh sdk from https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha6
2. Added libc++ in the link binary
![linkbinary](https://user-images.githubusercontent.com/32199575/37903173-90d5db34-3114-11e8-9f33-bb5b46e7c465.png)

3. Added Other Link flags
![otherlinker](https://user-images.githubusercontent.com/32199575/37903196-a35a63d8-3114-11e8-9a50-9af9917185c2.png)

4. Added Bridge Header
![bridgeheader](https://user-images.githubusercontent.com/32199575/37903210-b28835e2-3114-11e8-93ea-2ddea1afdb4d.png)

5. Here is my app delegates
![appdelegate](https://user-images.githubusercontent.com/32199575/37903228-c00c48e8-3114-11e8-9b32-95498483efd9.png)

Could please let us know where i am doing mistakes.

Thanks ,
Wahid Ali.

**Comment by rokob** [comment]
It looks like you do not have libc++ being linked still, you might have to clear derived data after adding that.

**Comment by RollbarExample** [comment]
Hi,

I have integrated Rollbar IOS Notifier successfully and I can able to send the crash log on the Rollbar console by following steps:

    1. Download the Rollbar framework(https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha6).
    2. Extract the Rollbar directory in the zip file to your Xcode project directory.
    3. In Xcode, select File -> Add Files to "[your project name]" and choose the Rollbar directory from step 2.
    4. Add the libstdc++.tbd into Linked Frameworks and Libraries.

  Thanks.

Wahid Ali

**Comment by jessewgibbs** [comment]
This should be fixed as of the 1.0.0 release.  I'm closing the issue.
