### ISSUE TITLE
Compiler error: RollbarNotifier.h not found

### ISSUE THREAD

**Issue by VicZhang1** [rollbar/rollbar-ios#70]
Hi,

I am trying to import Rollbar framework into my app, but I get compiler error **RollbarNotifier.h not found**. My steps are:

1. Download the zip file by using the link provided by [Rollbar for iOS](https://rollbar.com/docs/notifier/rollbar-ios/), the actual URL is https://github.com/rollbar/rollbar-ios/releases/download/v1.0.0-alpha2/Rollbar.zip
2. Unzip the **Rollbar.zip** file
3. Put the **Rollbar.framework** file to project root folder and add it to `Linked frameworks and libraries`
4. Import header `#import <Rollbar/Rollbar.h>`

see below:
![image](https://user-images.githubusercontent.com/2956318/36526055-9f8f1118-17e7-11e8-95ce-147b51daea0e.png)

Anything I did is wrong? or is the provided zip has a bug?

Thanks
-
Vic

**Comment by VicZhang1** [comment]
Looks like the latest release **v1.0.0-alpha5** will fix this issue, but while referencing it, I get more errors:
![image](https://user-images.githubusercontent.com/2956318/36526516-71a17104-17e9-11e8-9b51-834061d43cf1.png)

Any comments?

**Comment by VicZhang1** [comment]
I just replaced **v1.0.0-alpha2** with **v1.0.0-alpha5**

**Comment by VicZhang1** [comment]
> Undefined symbols for architecture x86_64:
>   "vtable for __cxxabiv1::__class_type_info", referenced from:
>       typeinfo for std::__1::default_delete<swift::Demangle::Node> in Rollbar(Demangle.o)
>   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
>   "typeinfo for std::__1::__shared_weak_count", referenced from:
>       typeinfo for std::__1::__shared_ptr_pointer<swift::Demangle::Node*, std::__1::default_delete<swift::Demangle::Node>, std::__1::allocator<swift::Demangle::Node> > in Rollbar(Demangle.o)
> ...

**Comment by rokob** [comment]
Yeah I know what this is, am working on it. To fix the specific issue you need to make the build process use the Obj-C++ compiler instead of the Obj-C one. Change any file to have the extension `.mm` instead of `.m` for instance `AppDelegate.mm`. But that will lead to other issues which I am working on now. I will update this when things are ready to go.

**Comment by rokob** [comment]
Okay, there is a new release up (https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha6) with a new zip file. You need to add `libc++` to your link binary with libraries phase and add `-ObjC` to your "Other Linker Flags" section. This is included now as part of the installation instructions in the README. There was a problem with the build process that generated the framework binary that I believe is now fixed. I'm going to leave this open issue for a bit in case other problems arise.

**Comment by VicZhang1** [comment]
@rokob Thanks for your update, using alpha6 version (referencing libc++.tbd and adding `-ObjC` to **Other Linker Flags** under **Build Settings*), I still get below errors:

> ld: warning: Auto-Linking supplied '/Users/VicZhang/WorkSpace/Demo/Rollbar.framework/Rollbar', framework linker option at /Users/VicZhang/WorkSpace/Demo/Rollbar.framework/Rollbar is not a dylib
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_RollbarConfiguration", referenced from:
>       objc-class-ref in AppDelegate.o
>   "_OBJC_CLASS_$_Rollbar", referenced from:
>       objc-class-ref in AppDelegate.o
>   "_OBJC_CLASS_$_RollbarTelemetry", referenced from:
>       objc-class-ref in AppDelegate.o
>       objc-class-ref in ViewController.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

My settings are:
1. Reference `libc++.tbd`
![image](https://user-images.githubusercontent.com/2956318/36627433-95141156-197d-11e8-8954-e7bcd714e870.png)

2. Add `-ObjC` flag
![image](https://user-images.githubusercontent.com/2956318/36627477-5173bebe-197e-11e8-9363-2276b0bf0c50.png)

Any comments?

**Comment by VicZhang1** [comment]
Hi @rokob , it works fine for me, but using alpha6, the notifier version is shown on Rollbar is `1.0.0-alpha5`, this may be a very minor issue.

However, it works for me now, thanks for your hard work.
